# Electric Book settings

# ----------------------------------------------------------
# Electric Book Manager
# ---------------------
electric-book-manager: enable
electric-book-manager-key: ""

# ----------------------------------------------------------
# Variants
# --------
# Set a variant of the work to output.
# A variant lets you override metadata and stylesheets and can be used,
# where `include metadata` has been used, in if statements like
# {% if variant == "somename" %}Variant text!{% endif %}
# Variant names must be one word, lowercase. Hyphens are allowed.
# Add variant book metadata to `_data/works`, and output settings here.
# --------------
# Active variant
# --------------
# Add the active variant (defined in `_data/works`) to activate it:
active-variant: ""
# ---------------
# Variant options
# ---------------
# Store settings for each variant.
# These have no effect unless an active-variant is set above.
variants:
  - variant: myvariant
    print-pdf-stylesheet: "print-pdf-variant.css"
    screen-pdf-stylesheet: ""
    web-stylesheet: "web-variant.css"
    epub-stylesheet: ""
    app-stylesheet: ""
  - variant: yourvariant

# ----------------------------------------------------------
# Indexing settings
# ------------
# Choose whether to disable dynamic indexing (false to disable).
# Disabling dynamic indexing will speed up outputs.
dynamic-indexing: true

# ----------------------------------------------------------
# Print-PDF settings
# ------------
print-pdf:
  # Choose between endnotes or footnotes (endnotes are default)
  # (You can also set this per markdown file with notes: footnotes,
  # or per endnote by adding .move-to-footnote to it.)
  notes: endnotes

# ----------------------------------------------------------
# Screen-PDF settings
# ------------
screen-pdf:
  # Choose between endnotes or footnotes (endnotes are default)
  # (You can also set this per markdown file with notes: footnotes,
  # or per endnote by adding .move-to-footnote to it.)
  notes: endnotes

# ----------------------------------------------------------
# Web settings
# ------------
web:
  # ----------
  # Pagination
  # ----------
  pagination: true
  # Choose one of:
  # - 'direction' for 'Next/Previous' pagination,
  # - 'titles' to show page titles at pagination,
  # - 'title-arrows' to show page titles and arrows,
  # - 'arrows' to use only arrows.
  pagination-type: "title-arrows"
  # --------
  # Masthead
  # --------
  # What kind of header do you want in the masthead? Options:
  # project-name, book-title, page-title, breadcrumbs
  # If not set, book-title is default.
  # Note that breadcrumbs slows your Jekyll build significantly.
  masthead:
    content: breadcrumbs
  # -----------------
  # Content accordion
  # -----------------
  # Do you want to collapse content sections in chapters on a
  # particular heading level? Default h2, set in accordion.js.
  # Set this to true to enable, or false to disable.
  accordion: false
  # Set the heading level that defines an accordion section
  accordion-level: h3
  # Should opening a new section close the others?
  accordion-auto-close: false
  # Enable annotation
  # You can have annotation on for development and/or for live.
  # Set each to either true or false
  annotator:
    development: false
    live: false
  # MathJax is activated in _config.yml. Further settings here.
  # At `source` choose local (`local`) MathJax.js or the CDN (`cdn`).
  mathjax:
    source: cdn
  # --------------
  # SVG management
  # --------------
  # By default on the web, we'll inject SVG as img tags into the page
  # so that you can control fonts and other SVG features with CSS.
  # This works for figure and image includes, and any image with
  # a 'inject-svg' class.
  # If you use injected SVGs, make sure their styles are inline,
  # or SVGs may end up 'sharing' styles for duplicated classes.
  # Advanced: see font-switching options in assets/js/svg-management.js
  # Set 'inject' to false to disable SVG injection.
  svg:
    inject: true
  # -----------------
  # Images management
  # -----------------
  images:
    # Load images only when they come into view?
    lazyload: true
  # -----------------
  # Bookmarks
  # -----------------
  bookmarks: true
  # --------------
  # Navigation
  # --------------
  nav:
    home:
      # On your landing page, should books in the nav expand
      # to include chapters? Expanding many chapters can
      # make your pages much bigger and slower. true/false
      expand-books: true
    project-nav:
      # Should your project navigation (in _data/nav.html)
      # appear before or after your book navigation?
      # Default is before.
      position: before
  # --------------
  # Search
  # --------------
  search:
    # Set where you want the 'Jump to first result' box
    # to show on pages linked from search results.
    # Define this as a querySelector string, targeting
    # the element before which the box should be shown.
    # Or for the main page heading, use the default 'mainHeading'.
    jump-box-location: "mainHeading"
    # If you need to point the search form at a different URL,
    # add it here in full, e.g. "https://google.com/search"
    search-url: ""
    # Set the parameter name to use for search URLs. Default is "query".
    # Google uses "q".
    search-url-parameter: ""
    # Add any extra, static parameters you might need
    # as a list, set `name` and `value` for each one. E.g.
    # static-url-parameters:
    #   - name: "as_sitesearch"
    #     value: "electricbookworks.com"
  # --------------
  # Monetization
  # --------------
  # If your book is going to use web monetization, add your
  # ILP pointer here. See _docs/advanced/monetization.md 
  # for more information about web monetization.
  monetization:
    enabled: false
    ilp-pointer: ""
  # --------------
  # Page tags and metadata
  # --------------
  page-tags:
    html-title-divider: " &ndash; "
  # --------------
  # SEO
  # --------------
  seo:
    # Use 'noindex' here to prevent Google (etc.) from
    # including your site in its search results.
    # The 'live: index' option applies only to builds
    # that use _config.live.yml. All default and other builds
    # are 'development' builds. Set 'development: noindex'
    # to prevent Google (etc.) from indexing those.
    indexing:
      development: index
      live: index

# ----------------------------------------------------------
# Epub settings
# -------------
epub:
  # -----
  # Fonts
  # -----
  # If you're embedding fonts, uncomment and list the font-file names here
  # and put the font files in _epub/fonts, not book/fonts
  # fonts:
  #   - CrimsonPro-Regular.otf
  #   - CrimsonPro-Italic.otf
  # -----------
  # Nav element
  # -----------
  # Every EPUB3 must have a nav element, like a TOC,
  # but you are allowed to hide it from view.
  # To hide the 'on the page' nav in epub, set this to 'true'.
  # Then you can put {% include toc %} anywhere in your epub
  # to generate a hidden nav element.
  hide-nav: false
  # --------
  # Metadata
  # --------
  # Settings that affect OPF metadata
  meta:
    # Turn project name in epub OPF metadata on/off
    project-name: false
    # Override the language in epub OPF metadata (use a subtag, e.g. en)
    language: ""
  # ----------
  # Javascript
  # ----------
  # Javascript in bundle.js is included by default.
  # If your epub should not include any Javascript,
  # set disabled to true. This does not disable MathJax.
  # Enable or disable MathJax in _config.
  # You may also want to exclude js in _config.epub.yml.
  javascript:
    disabled: false

# ----------------------------------------------------------
# App settings
# ------------
app:
  # ----------
  # Pagination
  # ----------
  pagination: true
  # Choose one of:
  # - 'direction' for 'Next/Previous' pagination,
  # - 'titles' to show page titles at pagination,
  # - 'title-arrows' to show page titles and arrows,
  # - 'arrows' to use only arrows.
  pagination-type: "title-arrows"
  # --------
  # Masthead
  # --------
  # What kind of header do you want in the masthead? Options:
  # site-name, book-title, page-title, breadcrumbs
  # If not set, book-title is default.
  # Note that breadcrumbs slows your Jekyll build significantly.
  masthead:
    content: breadcrumbs
  # -----------------
  # Content accordion
  # -----------------
  # Do you want to collapse content sections in chapters on a
  # particular heading level? Default h2, set in accordion.js.
  # Set this to true to enable, or false to disable.
  accordion: false
  # Set the heading level that defines an accordion section
  accordion-level: h3
  # Should opening a new section close the others?
  accordion-auto-close: false
  # -----------------
  # Bookmarks
  # -----------------
  bookmarks: true
  # --------------
  # Expansion file
  # --------------
  # If your book is huge and you need to store images
  # in an expansion file, edit these settings.
  google-play-expansion-file-enabled: false
  google-play-public-api-key: ""
  # --------------
  # Navigation
  # --------------
  nav:
    home:
      # On your landing page, should books in the nav expand
      # to include chapters? Expanding many chapters can
      # make your pages much bigger and slower. true/false
      expand-books: true
    project-nav:
      # Should your project navigation (in _data/nav.html)
      # appear before or after your book navigation?
      # Default is before.
      position: before
  # --------------
  # Search
  # --------------
  search:
    # Set where you want the 'Jump to first result' box
    # to show on pages linked from search results.
    # Define this as a querySelector string, targeting
    # the element before which the box should be shown.
    # Or for the main page heading, use the default 'mainHeading'.
    jump-box-location: "mainHeading"
    # If you need to point the search form at a different URL,
    # add it here in full, e.g. "https://google.com/search"
    # https://google.com/search
    search-url: ""
    # Set the parameter name to use for search URLs. Default is "query".
    # Google uses "q".
    search-url-parameter: ""
    # Add any extra, static parameters you might need
    # as a list, set `name` and `value` for each one. E.g.
    # static-url-parameters:
    #   - name: "as_sitesearch"
    #     value: "electricbookworks.com"
  # --------------
  # Page tags and metadata
  # --------------
  page-tags:
    html-title-divider: " &ndash; "

# ----------------------------------------------------------
# External media settings
# -----------------------
# If a large number of images makes your project too big,
# you can store your images in a separate location.
# See the docs for more information.
# Uncomment the following settings to activate remote media.
# remote-media:
#   development: ""
#   live: ""
# local-media:
#   development: ""

# ----------------------------------------------------------
# General output options
# ----------------------
# Redact elements with the 'redact' class: true or false
redact: false
