# Electric Book settings

# Electric Book Manager settings
# ----------------------------------------------------------
electric-book-manager: enable
electric-book-manager-key: ""

# Variant settings
# Set a variant of the work to output.
# A variant lets you override metadata and stylesheets and can be used,
# where `include metadata` has been used, in if statements like
# {% if variant == "somename" %}Variant text!{% endif %}
# Variant names must be one word, lowercase. Hyphens are allowed.
# Add variant book metadata to meta.yml, and output settings here.
# ----------------------------------------------------------
# Select the active variant:
# active-variant: myvariant
# ----------------------------------------------------------
# Store settings for each variant.
# These have no effect unless an active-variant is set above.
variants:
  - variant: myvariant
    print-pdf-stylesheet: "print-pdf-variant.css"
    screen-pdf-stylesheet: ""
    web-stylesheet: "web-variant.css"
    epub-stylesheet: ""
    app-stylesheet: ""
  - variant: yourvariant

# ----------------------------------------------------------
# Web settings
# ----------------------------------------------------------
# Turn pagination (next/previous) on or off
web:
  pagination: true
  # Choose 'direction' for 'Next/Previous' pagination,
  # or 'titles' to show page titles at pagination,
  # or 'arrows' to use only arrows.
  pagination-type: "arrows"

# ----------------------------------------------------------
# Epub settings
# ----------------------------------------------------------
epub:
# If you're embedding fonts, uncomment and list the font-file names here
# and put the font files in _epub/fonts, not book/fonts
#   fonts:
#     - Crimson-Roman.otf
#     - Crimson-Italic.otf
# Every EPUB3 must have a nav element, like a TOC,
# but you are allowed to hide it from view.
# To hide the 'on the page' nav in epub, set this to 'true'.
# Then you can put {% include toc %} anywhere in your epub
# to generate a hidden nav element.
  hide-nav: false
}

# ----------------------------------------------------------
# App settings
# ----------------------------------------------------------
# Turn pagination (next/previous) on or off
app:
  pagination: true
  # Choose 'direction' for 'Next/Previous' pagination,
  # or 'titles' to show page titles at pagination,
  # or 'arrows' to use only arrows.
  pagination-type: "arrows"
# If your book is huge and you need to store images
# in an expansion file, edit these settings.
google-play-expansion-file-enabled: false
google-play-public-api-key: ""
